name: CI shellcheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:latest
    steps:
      - name: '[debug] OS release & user'
        run: 'cat /etc/os-release; echo -n USER=; whoami'
      
      - name: Checkout (copy to runner/container)
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: apt-get update && apt-get install -y shellcheck

      - name: Run shellcheck
        run: shellcheck --severity=error *.sh
