name: ShellCheck CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: debian-latest
    steps:
      - name: Checkout (copy to runner)
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install shellcheck -y

      - name: Run shellcheck
        run: shellcheck --severity=error *.sh
